---
- name: lamp-server
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        state: present
        update_cache: yes
    - name: install php
      apt: 
        name: 
          - php 
          - libapache2-mod-php 
          - php-mysql
        state: present
      notify:
        - restart apache2
    - name: copy info.php to the destination
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
  handlers: 
    - name: restart apache2
      ansible.builtin.systemd: 
        name: apache2
        state: restarted

      